<a href="https://colab.research.google.com/github/weilipan/MachineLearing/blob/main/1_%E5%90%91%E9%87%8F%E8%88%87%E7%9F%A9%E9%99%A3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#利用串列來實作向量

In [5]:
#以串列來實作向量
A=[i for i in range(1,6)]
B=[i for i in range(6,11)]
def vector_add(a,b): #向量相加
  return [v_a+v_b for v_a,v_b in zip(a,b)]

def vector_dot(a,b): #向量內積
  return sum([v_a*v_b for v_a,v_b in zip(a,b)])

In [6]:
vector_add(A,B)

[7, 9, 11, 13, 15]

In [7]:
vector_dot(A,B)

130

# 利用numpy來處理

In [8]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [12]:
import numpy as np
A=np.array([i for i in range(1,7)])
B=np.array([i for i in range(7,13)])
print(f'向量相加：{A+B}')
print(f'純量、向量相乘：{3*A}')
print(f'向量相乘：{A*B}')
print(f'向量內積：{np.dot(A,B)}')
print(f'向量長度：{np.linalg.norm(A)}')

向量相加：[ 8 10 12 14 16 18]
純量、向量相乘：[ 3  6  9 12 15 18]
向量相乘：[ 7 16 27 40 55 72]
向量內積：217
向量長度：9.539392014169456


In [13]:
#Numpy提供多維度陣列ndarray,有三個主要屬性:維度(ndim)、形狀(shape)、
#數值型態(dtype)，預設的整數型態是int64,浮點數為float64
arr=np.array([i for i in range(1,7)])
print(arr.ndim)
print(arr.shape)#常用
print(arr.dtype)

1
(6,)
int64


In [14]:
#兩種改變陣列的形狀與維度的方法
arr.shape=2,3
print(arr)
arr1=arr.reshape(3,2)
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [15]:
#矩陣相乘
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,0,0],[0,1,1],[1,0,1]])
print(np.dot(A,B))#矩陣相乘
print(A.transpose())#矩陣轉置，也可用A.T
print(np.linalg.inv(B))#反矩陣

[[ 4  2  5]
 [10  5 11]]
[[1 4]
 [2 5]
 [3 6]]
[[ 1.  0.  0.]
 [ 1.  1. -1.]
 [-1.  0.  1.]]


In [16]:
#若矩陣為不可逆(singular)將沒有反矩陣，建議改用
try:
  inv=np.linalg.inv(B)
except np.linalg.LinAlgError:
  print('不可逆矩陣')

In [17]:
#轉置對一維陣列沒用
arr=np.array([1,2,3]) #一維陣列
print(arr.transpose())
arr=np.array([[1,2,3]]) #二維陣列
print(arr.transpose())

[1 2 3]
[[1]
 [2]
 [3]]


In [18]:
#拉平矩陣
A=np.array([[1,2,3],[4,5,6]])
A.flatten()#得到一維陣列

array([1, 2, 3, 4, 5, 6])

In [19]:
#得到二維陣列，-1代表自動使用所需的最大值
A.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6]])

In [20]:
#找最大最小值、平均值、變異數、標準差
print(np.min(A))
print(np.max(A))
print(np.mean(A))
print(np.var(A))
print(np.std(A))

1
6
3.5
2.9166666666666665
1.707825127659933
